const products = [
  // ========== Women's Fashion ==========
  {
    image: "/images/arrivals1-img.png",
    title: "Shiny Dress",
    brand: "Al Karam",
    price: "150.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: true,
    category: "Women's Fashion",
  },
  {
    image: "/images/arrivals2-img.png",
    title: "Long Dress",
    brand: "Al Karam",
    price: "500.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: true,
    category: "Women's Fashion",
  },
  {
    image: "/images/arrivals3-img.png",
    title: "Full Sweater",
    brand: "Al Karam",
    price: "200.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: true,
    category: "Women's Fashion",
  },
  {
    image: "/images/arrivals4-img.png",
    title: "White Dress",
    brand: "Al Karam",
    price: "175.000",
    rating: 4.5,
    reviewCount: "k",
    isSoldOut: true,
    category: "Women's Fashion",
  },
  {
    image: "/images/arrivals5-img.png",
    title: "Colorful Dress",
    brand: "Al Karam",
    price: "100.000",
    rating: 4.1,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women's Fashion",
  },
  {
    image: "/images/arrivals6-img.png",
    title: "White Shirt",
    brand: "Al Karam",
    price: "375.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: true,
    category: "Women's Fashion",
  },

  // ========== Men's Fashion ==========
  {
    image: "/images/arrivals1-img.png",
    title: "Men's Jacket",
    brand: "Zara",
    price: "400.000",
    rating: 4.8,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men's Fashion",
  },
  {
    image: "/images/arrivals2-img.png",
    title: "Denim Shirt",
    brand: "Levi's",
    price: "325.000",
    rating: 4.7,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men's Fashion",
  },
  {
    image: "/images/arrivals3-img.png",
    title: "Formal Suit",
    brand: "Hugo Boss",
    price: "900.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men's Fashion",
  },
  {
    image: "/images/arrivals4-img.png",
    title: "Casual Tee",
    brand: "Uniqlo",
    price: "100.000",
    rating: 4.3,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men's Fashion",
  },
  {
    image: "/images/arrivals5-img.png",
    title: "Slim Fit Pants",
    brand: "Zara",
    price: "350.000",
    rating: 4.6,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men's Fashion",
  },
  {
    image: "/images/arrivals6-img.png",
    title: "Winter Coat",
    brand: "H&M",
    price: "650.000",
    rating: 4.9,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men's Fashion",
  },

  // ========== Women Accessories ==========
  {
    image: "/images/arrivals1-img.png",
    title: "Women Handbag",
    brand: "Chanel",
    price: "650.000",
    rating: 4.7,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women Accessories",
  },
  {
    image: "/images/arrivals2-img.png",
    title: "Elegant Scarf",
    brand: "Zoya",
    price: "120.000",
    rating: 4.2,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women Accessories",
  },
  {
    image: "/images/arrivals3-img.png",
    title: "Gold Earrings",
    brand: "Swarovski",
    price: "800.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women Accessories",
  },
  {
    image: "/images/arrivals4-img.png",
    title: "Silk Hijab",
    brand: "Zoya",
    price: "150.000",
    rating: 4.4,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women Accessories",
  },
  {
    image: "/images/arrivals5-img.png",
    title: "Minimalist Watch",
    brand: "Daniel Wellington",
    price: "700.000",
    rating: 4.6,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women Accessories",
  },
  {
    image: "/images/arrivals6-img.png",
    title: "Crystal Ring",
    brand: "Swarovski",
    price: "900.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: false,
    category: "Women Accessories",
  },

  // ========== Men Accessories ==========
  {
    image: "/images/arrivals1-img.png",
    title: "Leather Belt",
    brand: "Gucci",
    price: "250.000",
    rating: 4.2,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men Accessories",
  },
  {
    image: "/images/arrivals2-img.png",
    title: "Aviator Sunglasses",
    brand: "Ray-Ban",
    price: "450.000",
    rating: 4.9,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men Accessories",
  },
  {
    image: "/images/arrivals3-img.png",
    title: "Smartwatch",
    brand: "Apple",
    price: "3.500.000",
    rating: 5,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men Accessories",
  },
  {
    image: "/images/arrivals4-img.png",
    title: "Wool Scarf",
    brand: "Uniqlo",
    price: "180.000",
    rating: 4.4,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men Accessories",
  },
  {
    image: "/images/arrivals5-img.png",
    title: "Men Bracelet",
    brand: "Fossil",
    price: "275.000",
    rating: 4.3,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men Accessories",
  },
  {
    image: "/images/arrivals6-img.png",
    title: "Digital Watch",
    brand: "Casio",
    price: "310.000",
    rating: 4.5,
    reviewCount: "k",
    isSoldOut: false,
    category: "Men Accessories",
  },

  // ========== Discont Deals ==========
  {
    image: "/images/arrivals1-img.png",
    title: "Discounted Dress",
    brand: "Al Karam",
    price: "100.000",
    rating: 3.9,
    reviewCount: "k",
    isSoldOut: true,
    category: "Discont Deals",
  },
  {
    image: "/images/arrivals2-img.png",
    title: "Clearance T-Shirt",
    brand: "H&M",
    price: "70.000",
    rating: 4.1,
    reviewCount: "k",
    isSoldOut: true,
    category: "Discont Deals",
  },
  {
    image: "/images/arrivals3-img.png",
    title: "Last Stock Skirt",
    brand: "Zalora",
    price: "95.000",
    rating: 4.0,
    reviewCount: "k",
    isSoldOut: true,
    category: "Discont Deals",
  },
  {
    image: "/images/arrivals4-img.png",
    title: "Promo Sneakers",
    brand: "Nike",
    price: "320.000",
    rating: 4.7,
    reviewCount: "k",
    isSoldOut: true,
    category: "Discont Deals",
  },
  {
    image: "/images/arrivals5-img.png",
    title: "Sale Hoodie",
    brand: "Adidas",
    price: "250.000",
    rating: 4.6,
    reviewCount: "k",
    isSoldOut: false,
    category: "Discont Deals",
  },
  {
    image: "/images/arrivals6-img.png",
    title: "Discount Jeans",
    brand: "Levi's",
    price: "275.000",
    rating: 4.2,
    reviewCount: "k",
    isSoldOut: false,
    category: "Discont Deals",
  },
];

export default products;
